### ISSUE TITLE
Unversioned field not being published

### ISSUE THREAD

**Issue by TheCodeKing** [kamsar/Unicorn#122]
We have a item containing an [unversioned] Sitecore field. When deployed via Unicorn with auto-publishing enabled the item is created correctly on Master, but never gets published to Web. Another [shared] field is correctly published.

**Comment by kamsar** [comment]
What Unicorn version? Ones prior to 3.1.4 might well explain this.

**Comment by TheCodeKing** [comment]
This was in 3.1.4.

**Comment by TheCodeKing** [comment]
Just to clarify, the item is published it's just the [unversioned] field value that's not appearing on web. A manual publish is needed to resolve.

**Comment by kamsar** [comment]
Probably something with https://github.com/kamsar/Unicorn/blob/master/src/Unicorn/Publishing/ManualPublishQueueHandler.cs#L35

**Comment by kamsar** [comment]
The auto publish was executing prior to an asynchronous cache clear. This resulted in stale caches being present for the publish, which meant it was publishing out of date content.

The fix is to drop a bomb on all the caches before we start publishing. This will be in the next version.

**Comment by kamsar** [comment]
This should be fixed in Unicorn 3.1.5-beta01, available on NuGet.

**Comment by TheCodeKing** [comment]
Great thanks, will give it a try.

**Comment by TheCodeKing** [comment]
Tried the latest 3.1.5-beta. Still having issues with unversioned fields not being published. It seems some are, but not all of them. 

All of the items in our case are being created as new items. They all exist in Master correctly, but on Web many items are missing the value for the unversioned field.

**Comment by kamsar** [comment]
I have been unable to replicate this. Here is my exact scenario:

* Choose a location synced by Unicorn (TpSync off, normal evaluator, in this case template + item same config)
* Create template with an unversioned text field, and an unversioned treelist.
* Create item based on said template.
* Set unversioned fields' values.
* Save serialized yml file for template instance and delete the template instance from Sitecore
* Verify that instance item is not in web DB and template is fully published
* Restore saved yml file, run Unicorn sync to restore serialized item with unversioned fields
* Review resulting item in web db after sync complete, note unversioned values all present

I also tried this with several language versions present, each with separate unversioned values. It always worked.

**Comment by kamsar** [comment]
Also tried it with:

* Updating the unversioned fields on an item that only was in master, which was then published by sync. Worked.
* Updating the unversioned fields on an item in both web and master. Also worked.

**Comment by TheCodeKing** [comment]
Could it be related to number of items being synced, or silently failing due to an error, possibly network related? We are deploying on Azure via Powershell and Azure DB throttles and drops connections if it gets to busy.

Here's the last part of the output. The unversioned fields are part of a dictionary.

`Debug: > Dictionary entries were altered during sync. Clearing dictionary caches...
Info: Projects\Vbs sync complete: 2838 items evaluated, 1836 items modified (1836 added, 0 updated, 0 recycled) in 524255ms (~184.7ms/item).`

**Comment by kamsar** [comment]
I tried this again tonight with 5 dictionary items, to no avail.

I did make one publishing alteration that went into 3.1.5 final, give that a shot and see if it fixed it.

**Comment by TheCodeKing** [comment]
Good work, seems to be fixed :)

**Comment by kamsar** [comment]
Excellent
